# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd4e56db87a66a8e45c36d35fea7ef161505313d5e592533c0ad24f0a5e5924023f3c65b3323d1b9818937599942b1cd3c0216c2f336d6e614d5269d006d59f

test:
  secret_key_base: e349464252577c7614ad5246a3451e65e06b9cb4b2e905f19fbee8e27ca4e16a0dfbcd0b5446e7eae427dc6db0933d68cc196c71064f3d9127b013b0b35d091d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
